services:
    ihlda:
        build:
            context: .
        image: ihlda
        container_name: ihlda
        network_mode: host
        tty: true
        volumes:
            - .:/workspaces/ihLDA
            - .jupyter:/root/.jupyter
        command: ["bash"]

